import './globals.css';
import Link from 'next/link';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { MonitorSmartphone, ShoppingCart } from 'lucide-react';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main className="flex flex-col justify-between min-h-screen bg-red-200">
					<header className=" fixed flex justify-between items-center shadow-xl bg-linear-to-b from-white to-gray-100 px-32 w-full h-20 ">
						<div className="flex items-center gap-2">
							<MonitorSmartphone />
							<Link href={'/'} className="font-bold text-2xl">
								Digital Shop
							</Link>
						</div>
						<div>
							<ShoppingCart />
						</div>
					</header>
					<div className="px-32 mt-28">{children}</div>
					<footer className='bg-black text-white flex justify-center py-1'>
						<p>&copy; All right Reserved By Masoud Anaraki</p>
					</footer>
				</main>
			</body>
		</html>
	);
}
