#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# this is what i fro stack overflow
# Turn off exit-on-error
set +e
pnpm exec commitlint --edit "$1" > /dev/null 2>&1
status=$?
# Turn exit-on-error back on
set -e

# 2) Your custom message:
if [ $status -ne 0 ]; then
    echo ""
    echo "❌ Invalid commit message format ❌"
    echo ""
    echo "✅ Correct Format ✅ →  <type>(<scope>): <subject>"
    echo ""
    echo "📑 Examples:"
    echo "    feat: add login functionality"
    echo "    fix(ui): correct button alignment"
    echo ""
    echo "💢 Allowed types: feat, fix, docs, style, refactor, perf, test, chore, ci"
    echo ""
    exit 1
fi